---
title: "3 layers autoencoder model - ANN2 library"
output: html_notebook
---

```{r}
#clear environment
rm(list=ls())
gc()
```


Creating autoencoder model using autoencoder() function from ANN2 library.
```{r}
if(huberCutOff){
  autoencoder <- autoencoder(
                        X = x_train_matrix, 
                        hiddenLayers = c(firstLayerUnits, SecodnLayerUnits, ThirdLayerUnits),
                        lossFunction = lossFunction,
                        dHuber = huberCutOff,
                        maxEpochs = maxEpochs,
                        standardize = FALSE,
                        learnRate = learningRate,
                        batchSize = batchSize,
                        momentum = momentum,
                        L2 = L2Regularization,
                        validLoss = TRUE,
                        verbose = TRUE,
                        robErrorCov = TRUE
                        )
}else{
    autoencoder <- autoencoder(
                        X = x_train_matrix, 
                        hiddenLayers = c(firstLayerUnits, SecodnLayerUnits, ThirdLayerUnits),
                        lossFunction = lossFunction,
                        maxEpochs = maxEpochs,
                        standardize = FALSE,
                        learnRate = learningRate,
                        batchSize = batchSize,
                        momentum = momentum,
                        L2 = L2Regularization,
                        validLoss = TRUE,
                        verbose = TRUE,
                        robErrorCov = TRUE
                        )
}
```

```{r}
plot(autoencoder)

rX <- reconstruct(autoencoder, x_train)

#difference between x_train and rX gives us anomalies in x_train dataset.
```