---
title: "Groups in time analysis"
output: html_notebook
---

First step is to load the training data and labels that are used to mark anomalies.

```{r}
data <- read.csv(file="../data/train_data.csv", header=TRUE, sep=",", row.names=NULL)
```

We want to check how big are the groups of packets that belong to the same category.

```{r}
data_frame <- data.frame(category=character(), count=numeric())
category <- ""
group_count <- 1
for (i in 1:nrow(data)) {
  if (category == data$category[i]) {
    group_count <- group_count + 1 
  } else {
    data_frame <- rbind(data_frame, data.frame(category=category, count=group_count))
    category <- data$category[i]
    group_count <- 1
  }
}
data_frame <- data_frame[-1, ]
data_frame <- data_frame %>% 
    group_by_('category') %>% 
    summarise(count = median(count))
getType <- function(x) {
  if (x['category'] == 'normal') {
    return('normal');
  } else if (x['category'] == 'smurf' || x['category'] == 'neptune') {
    return('ddos')
  } else {
    return('anomaly')
  }
}
data_frame$type <- apply(data_frame, 1, getType)
```

We make a bar chart out of data.

```{r}
ggplot(data_frame, aes(x=reorder(category, -count), y=count, fill=type)) + geom_bar(stat="identity") + theme(axis.text.x=element_text(angle=90)) + scale_y_log10() 
```
