---
title: "Categories distribution analysis"
output: html_notebook
---

First step is to import required libraries.

```{r}
require(ggplot2)
require(dplyr)
```

Next step is to load the training data and labels that are used to mark anomalies.

```{r}
data <- read.csv(file="../data/raw/creditcard.csv", header=TRUE, sep=",", row.names=NULL)
data_frame <- data.frame(data)
getType <- function(x) {
  if (x['Class'] == 0) {
    return('Normal');
  } else {
    return('Anomaly')
  }
}
data_frame$type <- apply(data_frame, 1, getType)
```

Then we extract categories that each row is labeled with and aggregate them.

```{r}

label_column_names <- setdiff(names(data_frame), names(which(sapply(data_frame ,is.numeric))))
for (column_name in label_column_names) {
  print(data_frame %>% 
    group_by_(column_name, 'type') %>% 
    summarise(count = n()) %>%
    ggplot(aes_string(x = column_name, y = 'count', fill = 'type')) + geom_bar(stat="identity") + theme(axis.text.x=element_text(angle=90)))
}
```